// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

DECL_FATTN_MMA_F16_CASE_KV(128, 128, 64, 1, GGML_TYPE_Q4_0);
DECL_FATTN_MMA_F16_CASE_KV(256, 256, 64, 1, GGML_TYPE_Q4_0);
